name: OpenAI PR Reviewer

on:
  pull_request:
    types: [opened]  # Only trigger on PR creation, not every push
  issue_comment:
    types: [created]  # Enable interactive mode

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  ai-review:
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@wic-reviewer'))
    runs-on: ubuntu-latest
    name: AI Code Review
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: OpenAI PR Reviewer
        uses: ./
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          app_id: ${{ secrets.WIC_APP_ID }}
          app_private_key: ${{ secrets.WIC_APP_PRIVATE_KEY }}
          app_installation_id: ${{ secrets.WIC_APP_INSTALLATION_ID }}
          model: 'gpt-4o-mini'  # Updated to use GPT-4o-mini with 128k context
          review_type: 'comprehensive'
          max_files: 10
          exclude_patterns: '*.json,*.md,*.txt,*.lock,*.svg,*.png,*.jpg,*.gif,*.zip,package-lock.json,node_modules/**,dist/*,*.d.ts,*.js.map'
          max_tokens: 4000