name: Test OpenAI PR Reviewer

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  ai-review:
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@wic-reviewer'))
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: OpenAI PR Reviewer
        uses: ./
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          model: 'gpt-4o-mini'  # Best cost/performance ratio with 128k context
          review_type: 'comprehensive'
          max_files: 5
          max_tokens: 2000
          exclude_patterns: '*.txt,*.lock,*.svg,*.png,*.jpg,*.gif,dist/*,*.d.ts,*.js.map'